apiVersion: apps/v1
kind: Deployment
metadata:
  name: jamesa
  labels:
    app: jamesa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jamesa
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: jamesa
    spec:
      containers:
      - name: jamesa
        image: gcr.io/lbg-training/jamesa-node-app-image:12
        ports:
        - containerPort: 80